Knx 2.0 generic dpt mapper
kgoderis/openhab2 pull request #9
Opened 2017-05-18 13:39 UTC by lewie

2017-05-18 17:40 UTC, kgoderis requested changes

2017-05-18 17:40 UTC, kgoderis commented on addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(KNXCoreTypeMapper.class);
We should in fact remove static here, and LOGGER should become again 'logger'

2017-05-18 17:40 UTC, kgoderis commented on addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
>          dptTypeMap.put(DPTXlatorBoolean.DPT_UPDOWN.getID(), UpDownType.class);
Can you explain a bit why we have these exceptions directly put into the dptTypeMap?

2017-05-18 17:40 UTC, kgoderis commented on addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
> +        final List<Class<?>> xlators = Arrays.<Class<?>> asList(DPTXlator1BitControlled.class,
should this not be static?

2017-05-18 20:28 UTC, lewie commented on addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(KNXCoreTypeMapper.class);
Thought about, but then some static function can not log, [like this.](https://github.com/kgoderis/openhab2/pull/9/files/e96c5042fbc8ccea702ac758a7b5815c2f3ed5b1#diff-0a73a0644601e4bd4e031b0907472063R936)

2017-05-18 20:37 UTC, lewie commented on addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
>          dptTypeMap.put(DPTXlatorBoolean.DPT_UPDOWN.getID(), UpDownType.class);
>dptMainTypeMap.put(1, OnOffType.class); 

responds generic inclusive (OnOffType). But there are datatypes that do not fit into that pattern(s). Exceptions which we have to put specially.

2017-05-18 20:41 UTC, lewie commented on addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
> +        final List<Class<?>> xlators = Arrays.<Class<?>> asList(DPTXlator1BitControlled.class,
It is in a static block:

```

    static {

        @SuppressWarnings("unused")
        final List<Class<?>> xlators = Arrays.<Class<?>> asList(DPTXlator1BitControlled.class,
                DPTXlator2ByteFloat.class, DPTXlator2ByteUnsigned.class, DPTXlator3BitControlled.class,
                DPTXlator4ByteFloat.class, DPTXlator4ByteSigned.class, DPTXlator4ByteUnsigned.class,
...
```

2017-05-18 20:53 UTC, lewie commented on addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
>          dptTypeMap.put(DPTXlatorBoolean.DPT_UPDOWN.getID(), UpDownType.class);
...here like *UpDownType*

2017-05-19 14:36 UTC, kgoderis commented on addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
>          dptTypeMap.put(DPTXlatorString.DPT_STRING_8859_1.getID(), StringType.class);
@lewie Ok, I was in fact looking at this line before, and here we have StringTYpe for the maintype, and also String for the exceptions. That's why I could not figure out what you were doing. So, does that mean that we do need those exception here in class 16?

2017-05-19 14:38 UTC, kgoderis commented on addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
> +        final List<Class<?>> xlators = Arrays.<Class<?>> asList(DPTXlator1BitControlled.class,
Ok missed that line #95

2017-05-19 16:06 UTC, lewie commented on addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(KNXCoreTypeMapper.class);
Is a private static "LOGGER" ok for you in this class?

2017-05-19 16:08 UTC, lewie commented on addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
>          dptTypeMap.put(DPTXlatorString.DPT_STRING_8859_1.getID(), StringType.class);
Oh yes, you are right. These Lines 376, 377 we do not need, changed.

2017-05-19 16:32 UTC, kgoderis commented on addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(KNXCoreTypeMapper.class);
Yes, there is no other option. Code guidelines prescribe a non static logger however

2017-05-19 16:39 UTC, merged